/**
 * The real 52-company outbound prospect list the user provided
 * ("DeployFleet — Reconciled Prospect Database (CRM Template)", Zambia
 * Haulage Target List, Aug 2026) — transcribed verbatim from the CSV,
 * not invented. Every row starts at pipeline stage 1 ("Researched": we
 * have public-directory-level facts, nobody has attempted contact yet)
 * per crm.ts's seedProspectsFromCsv(), source "outbound-cold-list".
 */

export interface ProspectSeedRow {
  name: string;
  contactName: string | null;
  contactRole: string | null;
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  location: string | null;
  estimatedFleetSizeRaw: string | null;
  primaryPainRaw: string | null;
  notes: string;
}

export const PROSPECT_SEED_ROWS: ProspectSeedRow[] = [
  { name: "Gomes Haulage Ltd", contactName: "General Management", contactRole: "Operations Director", phone: "+260 212 650 452", whatsapp: "+260 212 650 452", email: "info@gomeshaulage.com", location: "Plot 4083 Twalumba Close, Ndola (Copperbelt HQ) / Lusaka Depot", estimatedFleetSizeRaw: "Large/Enterprise (500-1000 employees)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Copper concentrate & heavy mining equipment transit across Lusaka-Ndola & SADC corridors." },
  { name: "Freight & Passenger Services Ltd (FPS / Hazida Group)", contactName: "Ismail Mulla / Emmanuel Simanda", contactRole: "Director Operations / Ops Manager", phone: "+260 211 287 695", whatsapp: "+260 968 679 439", email: "fps@freight.co.zm", location: "Plot 34390 Lumumba Rd (HQ) / Plot 8500 Katanga Rd, Chinika", estimatedFleetSizeRaw: "Large/Enterprise (100+ trucks)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Fuel tankers, crude oil & tri-axle semi-trailers running Lusaka-JHB, Beira, Dar es Salaam." },
  { name: "DSV Air & Sea Ltd (Zambia)", contactName: "Shakir Ismail", contactRole: "Country Director", phone: "+260 211 455 405", whatsapp: "+260 977 740 839", email: "Shakir.Ismail@dsv.com", location: "Plot 9466 Off Kafue Rd, Makeni / KKIA Freight Village", estimatedFleetSizeRaw: "Large/Enterprise (Global network / 30+ local fleet)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Multinational container haulage & project cargo hub across all major border posts." },
  { name: "Juba Transport Ltd", contactName: "Recruitment / Ops Dept", contactRole: "Fleet Operations Manager", phone: "+260 211 286 556", whatsapp: "+260 972 754 535", email: "info@jubatransport.co.zm", location: "Plot 1275 Off Mumbwa Rd, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (200+ tankers/trucks)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Hazardous cargo, fuel, acid, and explosives haulage across Copperbelt & DRC corridors." },
  { name: "Satwant Transport Ltd", contactName: "Mandeep de Brito", contactRole: "Operations Manager", phone: "+260 955 153 050", whatsapp: "+260 978 865 382", email: "mandeep@satwant.co.zm", location: "36 Los Angeles Rd, Makeni, Lusaka", estimatedFleetSizeRaw: "Large (45-50+ trucks)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General freight, cement, maize & cross-border transit to SA and Zimbabwe." },
  { name: "Time Trucking Ltd", contactName: "HR & Fleet Operations", contactRole: "Fleet / HR Manager", phone: "+260 211 272 179", whatsapp: "+260 211 272 179", email: "hrtime.trucking@gmail.com", location: "Plot 37175/REM Kafue Rd, Makeni, Lusaka", estimatedFleetSizeRaw: "Large (50+ trucks)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Dry cargo & tautliners operating across regional SADC corridors." },
  { name: "Carribean Transport Ltd", contactName: "Clifford Mugala", contactRole: "Operations Director", phone: "+260 977 623 678", whatsapp: "+260 971 023 241", email: "carribeanlogistics@inarainvestments.com", location: "Plot 289 Nampundwe Rd, Light Industrial Area, Lusaka", estimatedFleetSizeRaw: "Large (200+ trucks)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Large general freight operator with East Africa cross-border priority." },
  { name: "Africa Global Logistics (ex-Bolloré)", contactName: "Operations Manager", contactRole: "Logistics Lead", phone: "+260 211 246 191", whatsapp: "+260 211 246 191", email: "info@aglgroup.com", location: "Matero, Lusaka / Chingola Logistics Hub", estimatedFleetSizeRaw: "Large/Enterprise (Multinational)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Mining logistics hub & container loop operations into Katanga/DRC." },
  { name: "DHL International (Zambia) Ltd", contactName: "Sales & Logistics Team", contactRole: "Account Manager", phone: "+260 211 376 400", whatsapp: "+260 971 032 034", email: "zmsls@dhl.com", location: "Plot 2411 Cnr Makishi & Parirenyatwa Rds, Fairview, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Global fleet)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Express road distribution and air-ground cargo feeder routes across SADC." },
  { name: "Kuehne + Nagel (Zambia) Ltd", contactName: "Branch Management", contactRole: "Freight Forwarding Manager", phone: "+260 211 287 872", whatsapp: "+260 211 287 871", email: "info.lusaka@kuehne-nagel.com", location: "8131 Mwembeshi Rd, Light Industrial Area, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Global fleet)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Multimodal container logistics and cross-border road freight via Durban and Dar es Salaam." },
  { name: "Rangel Logistics & Transport (Zambia)", contactName: "Country Manager", contactRole: "Logistics Manager", phone: "+260 765 192 354", whatsapp: "+260 765 192 354", email: "zambia@rangel.com", location: "Lusaka Warehouse Facility / Office", estimatedFleetSizeRaw: "Large/Enterprise (Multinational)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Reefer cargo, cross-border groupage (LTL), and regional SADC distribution." },
  { name: "Swift Freight International (DSV Swift)", contactName: "Vishal Joshi", contactRole: "General Manager", phone: "+260 211 235 093", whatsapp: "+260 211 235 143", email: "vishal.joshi@swiftfreight.com", location: "Suite 4, Church Rd / Raphael Kombe Rd, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Regional network)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Cross-border freight forwarding and container transit into East & Central Africa." },
  { name: "CEVA Logistics Zambia", contactName: "Regional Fleet Manager", contactRole: "Operations Lead", phone: "+260 212 614 465", whatsapp: "+260 212 614 465", email: "info@cevalogistics.com", location: "Plot 80 Nyerere Rd, Kitwe / Lusaka Operations", estimatedFleetSizeRaw: "Large/Enterprise (Multinational)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Project cargo and cross-border ground transport servicing mining corridors." },
  { name: "Expeditors Zambia", contactName: "Vikram Neruturi", contactRole: "Branch Manager", phone: "+260 211 243 595", whatsapp: "+260 978 298 277", email: "vikram@gfslog.com", location: "Stand 7437 Mungwi Rd, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Multinational)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Air-ocean-land freight forwarding and customs clearance across Zambian borders." },
  { name: "Hellmann Worldwide Logistics Zambia", contactName: "Raymond Carter-Johnson", contactRole: "Operations Manager", phone: "+260 211 238 325", whatsapp: "+260 211 238 325", email: "Raymond.Carter-Johnson@hellmann.com", location: "Plot 3056 Makishi Rd, Fairview, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Multinational)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Global supply chain and road transit connecting Dar es Salaam, Beira, and Durban corridors." },
  { name: "NAC 2000 Corporation Ltd", contactName: "Tasila Phiri", contactRole: "Customer Service Manager", phone: "+260 211 271 012", whatsapp: "+260 979 440 000", email: "tasila.phiri@nac2000.com", location: "Site 15 Freight Village, KKIA, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Airport-based fleet)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Air freight ground handling and road feeder fleet to Copperbelt and DRC." },
  { name: "Mercury Express Logistics", contactName: "Enquiries Team", contactRole: "Logistics Desk", phone: "+260 211 257 361", whatsapp: "+260 971 269 390", email: "enquiries@mercury.co.zm", location: "Plot 6392 Dundudza Chididza Rd, Longacres, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (Multiple branches)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Express haulage and cross-border distribution across SADC region." },
  { name: "Southern Logix (Southern Diesel division)", contactName: "Logistics Desk", contactRole: "Fleet Lead", phone: "+260 972 121 218", whatsapp: "+263 774 893 716", email: "logistics@southerndiesel.org", location: "397a Makeni Rd, Makeni, Lusaka", estimatedFleetSizeRaw: "Large/Enterprise (SADC-wide fuel fleet)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "SADC petroleum tankers (PMS/Diesel) operating under PATROM compliance." },
  { name: "Agrofuel Investments Ltd (Agrofuel Ltd)", contactName: "Rashid Ismail / Evans", contactRole: "Managing Director / Ops", phone: "+260 955 800 479", whatsapp: "+260 955 800 479", email: "evans@agrofuelinvestments.com", location: "Plot 8489 Lumumba Rd, Lusaka", estimatedFleetSizeRaw: "Medium-Large", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Petroleum tankers and bulk agricultural transport across Zambia and region." },
  { name: "Dalsan Group", contactName: "Logistics Management", contactRole: "Operations Desk", phone: "+260 760 285 253", whatsapp: "+260 777 262 210", email: "info@dalsangroup.com", location: "Lusaka Central Operations / Depot", estimatedFleetSizeRaw: "Medium (State-of-the-art fleet)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Bulk fuel delivery and tanker distribution to Copperbelt and regional hubs." },
  { name: "Forlan Logistics Ltd", contactName: "Sales / Spares Desk", contactRole: "Operations Manager", phone: "+260 967 929 253", whatsapp: "+260 762 126 716", email: "flcardealers@gmail.com", location: "Plot 3148 Zecco Bldg, Mukwa Rd, Heavy Industrial Area, Lusaka", estimatedFleetSizeRaw: "Medium (Truck service center + fleet)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Container haulage, vehicle import/export, truck repair and spares hub." },
  { name: "Brunelli African Logistics Ltd", contactName: "Directory Lead", contactRole: "Ops Manager", phone: "+260 211 246 191", whatsapp: "+260 211 246 191", email: "info@brunelli.co.zm", location: "5267 Mukwa Rd, Heavy Industrial Area, Lusaka", estimatedFleetSizeRaw: "Medium (Established operator)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General haulage and cross-border SADC transport out of Mukwa Road yard." },
  { name: "Hill & Delamain (Zambia) Ltd", contactName: "Lusaka Manager", contactRole: "Branch Manager", phone: "+260 211 286 480", whatsapp: "+260 211 286 491", email: "lusaka.manager@hdcargo.co.zm", location: "Kachidza Rd, Light Industrial Area / KKIA Freight Village", estimatedFleetSizeRaw: "Medium (Established forwarder)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Air-road freight distribution and project cargo management across SADC." },
  { name: "Worldmasters Freight Logistics Ltd", contactName: "Operations Desk", contactRole: "General Manager", phone: "+260 211 234 970", whatsapp: "+260 977 849 492", email: "world@microlink.zm", location: "3B 2nd Floor Chiparamba House, Chiparamba Rd, Lusaka", estimatedFleetSizeRaw: "Medium (Established forwarder)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Container haulage and road-air-sea freight forwarder connecting Dar and Durban." },
  { name: "Continental Freight Services Ltd (Hazida Group)", contactName: "Operations Manager", contactRole: "Fleet Lead", phone: "+260 211 287 695", whatsapp: "+260 211 286 963", email: "fps@freight.co.zm", location: "Plot 8484/85 Lumumba Rd, Lusaka", estimatedFleetSizeRaw: "Medium (Clearing & haulage)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Customs clearing and road haulage operating across all major Zambian border posts." },
  { name: "Customised Clearing & Forwarding Ltd", contactName: "Siri / Ops Manager", contactRole: "Operations Lead", phone: "+260 966 334 840", whatsapp: "+260 966 334 840", email: "siri@ccfzambia.com", location: "Plot 3138 Muyantanshi Rd, Lusaka", estimatedFleetSizeRaw: "Medium (Full licence operator)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Container haulage and customs transit forwarding along Dar es Salaam & Durban corridors." },
  { name: "Lift and Shift Trucking Zambia Ltd", contactName: "Logistics Coordinator", contactRole: "Fleet Lead", phone: "+260 211 272 179", whatsapp: "+260 211 272 179", email: "liftnshifttrucking@gmail.com", location: "Plot 687 off Makeni Rd, Lusaka", estimatedFleetSizeRaw: "Medium-Large", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Heavy cargo and abnormal load transport specialists across cross-border routes." },
  { name: "Move Us Zambia", contactName: "Operations Team", contactRole: "Customer Manager", phone: "+260 211 230 692", whatsapp: "+260 974 549 729", email: "info@moveuszambia.com", location: "Plot 6 Lutanda Flat, Kutwe Rd, Villa Elizabetha, Lusaka", estimatedFleetSizeRaw: "Small-Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Relocations and general freight transport operating locally and regionally." },
  { name: "Welvix Global Logistics", contactName: "Zambia Desk", contactRole: "Ops Lead", phone: "+260 764 001 551", whatsapp: "+264 81 302 8249", email: "info@zambiawide.com", location: "A Nampundwe Rd, Chinika, Lusaka", estimatedFleetSizeRaw: "Medium (Regional network)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Walvis Bay corridor specialists with road transport and project cargo facilities." },
  { name: "Chalino Logistics & Business Solutions", contactName: "Operations Lead", contactRole: "Manager", phone: "+260 977 123 456", whatsapp: "+260 977 123 456", email: "info@chalinologistics.com", location: "Plot 6980 Katanga Rd, Chinika, Lusaka", estimatedFleetSizeRaw: "Small-Medium (Katanga Rd yard)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General haulage and road freight out of Katanga Road industrial hub." },
  { name: "Vasi Transport Lda", contactName: "Yard Manager", contactRole: "Fleet Lead", phone: "+260 211 287 000", whatsapp: "+260 211 287 000", email: "info@vasitransport.com", location: "7183 Kachidza Rd, Heavy Industrial Area, Lusaka", estimatedFleetSizeRaw: "Small-Medium (Kachidza Rd depot)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General haulage and regional distribution operating out of Kachidza Road." },
  { name: "Kintech Investments", contactName: "Operations Desk", contactRole: "Yard Manager", phone: "+260 211 270 000", whatsapp: "+260 211 270 000", email: "info@kintech.zm", location: "Plot 20/397A Chipwenupwenu Rd, Makeni, Lusaka", estimatedFleetSizeRaw: "Small-Medium (Makeni operator)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General haulage and industrial transport based in Makeni." },
  { name: "Delta Trucking Ltd", contactName: "Fleet Operations", contactRole: "Depot Lead", phone: "+260 211 260 000", whatsapp: "+260 211 260 000", email: "info@deltatrucking.zm", location: "22881 Leopards Hill Rd, Lusaka", estimatedFleetSizeRaw: "Small-Medium (Leopards Hill area)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "General cargo, tippers, and construction haulage across Lusaka corridors." },
  { name: "Cargo Management & Logistics Zambia Ltd", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 966 999 219", whatsapp: "+260 966 999 219", email: "info@cargomanagement.zm", location: "Plot F397a, Makeni Rd, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Freight forwarding and regional road transport out of Makeni Road depot." },
  { name: "Roverline Marketing and Logistics Ltd", contactName: "Fleet Desk", contactRole: "Manager", phone: "+260 211 289 641", whatsapp: "+260 211 289 641", email: "info@roferline.zm", location: "Linda Rd, Makeni Bonaventure, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Marketing logistics and haulage serving Makeni Bonaventure area." },
  { name: "Prodrive Trucking", contactName: "Manager", contactRole: "Fleet Supervisor", phone: "+260 971 814 181", whatsapp: "+260 971 814 181", email: "info@prodrivetrucking.zm", location: "34133 Makishi Rd, Fairview, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Local and inter-city trucking operating out of Makishi Road." },
  { name: "Yeshua Logistics", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 977 303 565", whatsapp: "+260 977 303 565", email: "info@yeshualogistics.zm", location: "Findeco House 22nd Floor, Cairo Rd, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Cross-border logistics and regional haulage forwarding." },
  { name: "J&J Transport Zambia Ltd", contactName: "Oscar Gutierrez", contactRole: "Country Director / Ops", phone: "+260 972 596 371", whatsapp: "+260 972 596 371", email: "info@jjzam.com", location: "Plot 50, 15 Linda Rd, Bonaventure, Lusaka", estimatedFleetSizeRaw: "Medium-Large", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Regional general transport and flatbed container haulage." },
  { name: "4PL Africa", contactName: "Operations Lead", contactRole: "Logistics Manager", phone: "+260 96 381 8887", whatsapp: "+260 96 381 8887", email: "info@fourpl.com", location: "Plot 10020 Mwembeshi Rd, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "4PL logistics management and regional freight forwarding." },
  { name: "Hakika Logistics Ltd", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 761 444 444", whatsapp: "+260 761 444 444", email: "info@hakika.zm", location: "Leopards Hill Rd area, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Regional haulage and logistics serving SADC routes." },
  { name: "Intercontinental Relocations Ltd", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 966 452 525", whatsapp: "+260 966 452 525", email: "info@intercontinental.zm", location: "Avondale area, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Relocations, heavy cargo, and regional transport." },
  { name: "Sable Transport Ltd", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 21 625 6255", whatsapp: "+260 21 625 6255", email: "info@sabletransport.zm", location: "Lusaka Operations / Yard", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Construction transport, tippers, and civil haulage." },
  { name: "A M Motors Ltd", contactName: "Fleet Operations", contactRole: "Manager", phone: "+260 21 184 8021", whatsapp: "+260 21 184 8021", email: "info@ammotors.zm", location: "Great North Rd, Kabangwe, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Heavy haulage and commercial truck maintenance on Great North Road." },
  { name: "Wakah Logistics Zambia", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 574 040 980", whatsapp: "+260 574 040 980", email: "info@wakahlogistics.zm", location: "Intercity HQ, Lusaka", estimatedFleetSizeRaw: "Medium-Large", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Cross-border passenger-freight and East/Southern Africa express routes." },
  { name: "Discovery Freight & Logistics", contactName: "Customs Desk", contactRole: "Operations Lead", phone: "+260 211 260 100", whatsapp: "+260 211 260 100", email: "info@discovery.co.zm", location: "Chalata Rd, Woodlands Extension, Lusaka", estimatedFleetSizeRaw: "Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Customs clearance, road/rail freight forwarding across all Zambian borders." },
  { name: "Circle Transtra International", contactName: "Operations Manager", contactRole: "Freight Lead", phone: "+260 211 280 100", whatsapp: "+260 211 280 100", email: "info@ctizambia.com", location: "Nsato Rd, Lusaka", estimatedFleetSizeRaw: "Large (8000+ loads/mo)", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "High-volume freight forwarding and cross-border haulage." },
  { name: "Buks Haulage Ltd (BHL)", contactName: "Enquiries Desk", contactRole: "Operations Manager", phone: "+260 212 650 000", whatsapp: "+260 212 650 000", email: "enquiries@bhl.co.zm", location: "Lusaka Operations / Solwezi Base", estimatedFleetSizeRaw: "Large/Enterprise", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Mining haulage, heavy cargo, and regional mining corridor transport." },
  { name: "HGC Transport & Logistics", contactName: "Operations Desk", contactRole: "Fleet Manager", phone: "+260 211 290 000", whatsapp: "+260 211 290 000", email: "info@hgc.co.zm", location: "Lusaka Depot / Zambia Ops", estimatedFleetSizeRaw: "Enterprise (600+ tankers)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Pan-African fuel tankers, LPG, and mining flatbeds." },
  { name: "Exitrans Logistics", contactName: "Operations Desk", contactRole: "Fleet Lead", phone: "+260 211 285 000", whatsapp: "+260 211 285 000", email: "info@exitrans.zm", location: "Lusaka Operations Yard", estimatedFleetSizeRaw: "Large (Diversified fleet)", primaryPainRaw: "Driver cash advances & transit fuel leakage", notes: "Petroleum tankers, acid/chemical transport, tippers, and reefers." },
  { name: "Rakach Logistics", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 211 220 000", whatsapp: "+260 211 220 000", email: "info@rakach.zm", location: "Plot 347 Premium House, Great North Rd, Lusaka", estimatedFleetSizeRaw: "Small-Medium", primaryPainRaw: "Border checkpoint document expiries & road fines", notes: "Northern Corridor transit specialists (Lusaka-Nakonde-Tanzania)." },
  { name: "Double C Logistics", contactName: "Operations Desk", contactRole: "Manager", phone: "+260 977 623 678", whatsapp: "+260 977 623 678", email: "doubleclogistics@outlook.com", location: "Plot 12720 Mumbwa Rd, Lusaka", estimatedFleetSizeRaw: "Small-Medium", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Road transport and regional logistics operating on Mumbwa Road." },
  { name: "Lightways Investments Ltd", contactName: "Logistics Desk", contactRole: "Manager", phone: "+260 962 317 202", whatsapp: "+260 962 317 202", email: "lightways@lightways.net", location: "Plot 397a Makeni Truck Inn, Lusaka", estimatedFleetSizeRaw: "Small (Makeni Truck Inn base)", primaryPainRaw: "Cost-Per-Kilometer (CPKM) visibility & maintenance untracked costs", notes: "Truck stop, logistics, and Makeni area distribution." },
];
